---
inherit_from: .rubocop_todo.yml

require:
- rubocop-performance
- rubocop-rspec
AllCops:
  NewCops: enable
  DisplayCopNames: true
  ExtraDetails: true
  DisplayStyleGuide: true
  TargetRubyVersion: '2.7'
  Include:
  - "**/*.rb"
  Exclude:
  - bin/*
  - ".vendor/**/*"
  - "**/Gemfile"
  - "**/Rakefile"
  - pkg/**/*
  - spec/fixtures/**/*
  - vendor/**/*
  - "**/Puppetfile"
  - "**/Vagrantfile"
  - "**/Guardfile"
Layout/LineLength:
  Description: People have wide screens, use them.
  Max: 310
